### ISSUE TITLE
BUG: Back to Top button is not working

### ISSUE THREAD

**Issue by arpy8** [Suchitra-Sahoo/AgriLearnNetwork#743] opened 2024-06-06 22:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The back to top button is not functional in the website currently. I would like to fix it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment] 2024-06-07 05:08
Please don't raise a PR before the issue is assigned to you. Also i have just checked and back to top button is working totally fine.

**Closed by Suchitra-Sahoo** 2024-06-07 05:08 UTC
